# Generated by Django 4.0.4 on 2022-05-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roofingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roofinglead',
            old_name='converstaion_finance',
            new_name='conversation_finance',
        ),
    ]
