# Generated by Django 4.0.4 on 2022-05-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofingapp', '0002_rename_converstaion_finance_roofinglead_conversation_finance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roofinglead',
            name='home_size',
            field=models.CharField(max_length=100),
        ),
    ]
