# Generated by Django 3.2.13 on 2022-05-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roofingapp', '0004_remove_roofinglead_apointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roofinglead',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='roofinglead',
            name='last_name',
        ),
    ]
